// styles/homeStyles.js
import { StyleSheet } from "react-native";
import { FONTS, DARK } from "../constants/theme";

const makeStyles = (colors) =>
  StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.bg0 },
    scroll: { flex: 1 },

    heroCard: {
      margin: 16,
      backgroundColor: DARK.bg2, // Always dark (design spec)
      borderRadius: 22,
      borderWidth: 0.5,
      borderColor: DARK.border2,
      padding: 20,
    },
    heroLabel: {
      fontSize: 9,
      letterSpacing: 2.5,
      opacity: 0.4,
      fontFamily: FONTS.bold,
      color: DARK.text1,
      fontWeight: "700",
    },
    heroAmount: {
      fontSize: 36,
      fontWeight: "800",
      letterSpacing: -1.5,
      fontFamily: FONTS.bold,
      color: DARK.text1,
      marginTop: 6,
      marginBottom: 2,
    },
    heroCur: { fontSize: 16, opacity: 0.4, color: DARK.text1 },
    heroSub: {
      fontSize: 10,
      fontWeight: "600",
      color: colors.success,
      opacity: 0.9,
      fontFamily: FONTS.medium,
    },

    pillRow: { flexDirection: "row", gap: 8, marginTop: 14 },
    pill: {
      flex: 1,
      backgroundColor: colors.glassPill,
      borderRadius: 10,
      padding: 8,
    },
    pillLabel: {
      fontSize: 8,
      letterSpacing: 1.5,
      opacity: 0.4,
      fontWeight: "700",
      fontFamily: FONTS.bold,
      color: DARK.text1,
    },
    pillVal: {
      fontSize: 13,
      fontWeight: "800",
      letterSpacing: -0.3,
      fontFamily: FONTS.bold,
      marginTop: 3,
    },

    // Add shortcut row (Home)
    addRow: {
      marginHorizontal: 16,
      marginBottom: 12,
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 16,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    addRowLeft: { flexDirection: "row", alignItems: "center", gap: 10 },
    addRowIcon: {
      width: 30,
      height: 30,
      borderRadius: 10,
      backgroundColor: colors.accentDim,
      alignItems: "center",
      justifyContent: "center",
    },
    addRowTitle: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.text1,
      letterSpacing: -0.1,
      fontFamily: FONTS.bold,
    },
    addRowSub: {
      fontSize: 9,
      fontWeight: "500",
      color: colors.text3,
      marginTop: 1,
      fontFamily: FONTS.medium,
    },
    addRowArrow: { fontSize: 16, color: colors.text3, fontWeight: "600" },

    secHead: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 8,
    },
    secTitle: { fontSize: 12, fontWeight: "700", color: colors.text1, fontFamily: FONTS.bold },
    secMore: { fontSize: 10, fontWeight: "600", color: colors.accent, letterSpacing: 1, fontFamily: FONTS.semibold },

    emptyBox: {
      margin: 20,
      padding: 24,
      backgroundColor: colors.bg3,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
    },
    emptyText: {
      color: colors.text3,
      opacity: 0.5,
      textAlign: "center",
      fontSize: 13,
      lineHeight: 22,
      fontFamily: FONTS.regular,
    },

    txItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 8,
      gap: 12,
      borderTopWidth: 0.5,
      borderTopColor: colors.border,
    },
    txIcon: {
      width: 34,
      height: 34,
      borderRadius: 11,
      backgroundColor: colors.accentDim,
      alignItems: "center",
      justifyContent: "center",
    },
    txEmoji: { fontSize: 18 },
    txInfo: { flex: 1 },
    txName: { fontSize: 12, fontWeight: "700", color: colors.text1, fontFamily: FONTS.bold },
    txMeta: {
      fontSize: 9,
      fontWeight: "500",
      color: colors.text3,
      opacity: 0.7,
      marginTop: 2,
      fontFamily: FONTS.medium,
    },
    txAmount: { fontSize: 13, fontWeight: "800", letterSpacing: -0.3, fontFamily: FONTS.bold },

    bottomNav: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: colors.bg1,
      borderTopWidth: 0.5,
      borderTopColor: colors.border,
      paddingTop: 8,
      paddingBottom: 28,
      flexDirection: "row",
    },

    navItem: { flex: 1, alignItems: "center", justifyContent: "center", gap: 3 },
    navIcon: { fontSize: 20, opacity: 0.3, textAlign: "center" },
    navIconActive: { opacity: 1 },
    navDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: colors.accent, opacity: 0 },
    navDotActive: { opacity: 1 },
    navLabel: {
      fontSize: 8,
      fontWeight: "600",
      color: colors.text2,
      opacity: 0.3,
      letterSpacing: 1,
      textTransform: "uppercase",
      fontFamily: FONTS.medium,
      marginTop: 1,
    },
    navLabelActive: { color: colors.accent, opacity: 1 },

    navPlusBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.accent,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 2,
    },
    navPlusBtnInactive: { opacity: 0.6 },
    navPlusLabel: {
      fontSize: 8,
      fontWeight: "700",
      color: colors.accent,
      marginTop: 2,
      fontFamily: FONTS.bold,
      opacity: 1,
    },
    navPlusLabelInactive: { opacity: 0.6 },
  });

export default makeStyles;
