import { StyleSheet } from "react-native";

const makeStyles = (colors) =>
  StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.bg0 },
    header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 4 },
    title: { fontSize: 24, color: colors.textPrimary, fontWeight: "800" },
    subtitle: { fontSize: 11, color: colors.silver, opacity: 0.5, marginTop: 2 },
    monthRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
      paddingVertical: 12,
    },
    monthArrow: {
      width: 28,
      height: 28,
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
      borderRadius: 9,
      alignItems: "center",
      justifyContent: "center",
    },
    monthArrowText: { fontSize: 20, color: colors.silver },
    monthName: {
      fontSize: 11,
      color: colors.text1,
      fontWeight: "700",
      letterSpacing: 0.8,
    },
    summaryRow: {
      flexDirection: "row",
      gap: 8,
      paddingHorizontal: 20,
      marginBottom: 10,
    },
    summaryCard: {
      flex: 1,
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
      borderRadius: 14,
      padding: 10,
    },
    summaryLabel: {
      fontSize: 7,
      color: colors.text1,
      opacity: 0.5,
      letterSpacing: 1,
      fontWeight: "700",
    },
    summaryAmount: {
      fontSize: 14,
      fontWeight: "800",
      marginTop: 6,
      letterSpacing: -0.4,
    },
    balanceCard: {
      marginHorizontal: 20,
      marginBottom: 20,
      backgroundColor: colors.bg2,
      borderWidth: 0.5,
      borderColor: colors.border2,
      borderRadius: 18,
      padding: 18,
    },
    balanceLabel: {
      fontSize: 9,
      color: colors.silver,
      opacity: 0.5,
      letterSpacing: 2.5,
    },
    balanceAmount: {
      fontSize: 34,
      fontWeight: "800",
      marginTop: 6,
      letterSpacing: -1.5,
    },
    heroAmountRow: {
      flexDirection: "row",
      alignItems: "baseline",
      gap: 4,
      marginTop: 6,
      marginBottom: 2,
    },
    heroCur: {
      fontSize: 18,
      fontWeight: "400",
      color: colors.text1,
      opacity: 0.4,
    },
    balanceSub: {
      fontSize: 11,
      color: colors.silver,
      opacity: 0.4,
      marginTop: 4,
    },
    section: { paddingHorizontal: 20, marginBottom: 20 },
    sectionTitle: { fontSize: 13, color: colors.textPrimary, fontWeight: "600", marginBottom: 12 },
    emptyBox: {
      padding: 20,
      backgroundColor: colors.bg3,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: "center",
    },
    emptyText: { fontSize: 12, color: colors.silver, opacity: 0.5 },
    catRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginBottom: 12,
    },
    catLeft: { flexDirection: "row", alignItems: "center", gap: 10, width: 130 },
    catEmoji: { fontSize: 22 },
    catName: { fontSize: 12, color: colors.textPrimary, fontWeight: "500" },
    catAmount: { fontSize: 10, color: colors.silver, opacity: 0.5, marginTop: 1 },
    catBarWrap: { flex: 1, height: 4, backgroundColor: colors.border, borderRadius: 99 },
    catBar: { height: "100%", borderRadius: 99, backgroundColor: colors.accent },
    catPercent: { fontSize: 9, color: colors.text2, fontWeight: "700", width: 32, textAlign: "right" },
    weekCompareTitle: {
      fontSize: 13,
      color: colors.textPrimary,
      fontWeight: "700",
      letterSpacing: 1,
      marginBottom: 12,
      textTransform: "uppercase",
    },
    weekRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 10 },
    weekLabel: { width: 60, fontSize: 10, color: colors.silver, opacity: 0.6, fontWeight: "600" },
    weekBarTrack: {
      flex: 1,
      height: 5,
      backgroundColor: colors.bg1,
      borderRadius: 3,
      overflow: "hidden",
      position: "relative",
    },
    weekBarExpense: {
      height: "100%",
      borderRadius: 3,
      backgroundColor: colors.accent,
      position: "absolute",
      left: 0,
      top: 0,
    },
    weekBarIncome: {
      height: "100%",
      borderRadius: 3,
      backgroundColor: colors.success,
      position: "absolute",
      left: 0,
      top: 0,
      opacity: 0.95,
    },
    weekValue: { width: 70, fontSize: 10, color: colors.silver, opacity: 0.6, textAlign: "right", fontWeight: "600" },
    txItem: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 8,
      gap: 12,
      borderTopWidth: 0.5,
      borderTopColor: colors.border,
    },
    txIcon: {
      width: 34,
      height: 34,
      borderRadius: 11,
      backgroundColor: colors.accentDim,
      alignItems: "center",
      justifyContent: "center",
    },
    txEmoji: { fontSize: 16 },
    txInfo: { flex: 1 },
    txName: { fontSize: 12, color: colors.text1, fontWeight: "700" },
    txMeta: { fontSize: 9, color: colors.text3, opacity: 0.7, marginTop: 2, fontWeight: "500" },
    txAmount: { fontSize: 13, fontWeight: "800", letterSpacing: -0.3 },
    modalOverlay: { flex: 1, backgroundColor: colors.modalOverlay, justifyContent: "flex-end" },
    modalBox: { backgroundColor: colors.bg1, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24, borderTopWidth: 1, borderColor: colors.border },
    modalTitle: { fontSize: 18, color: colors.textPrimary, fontWeight: "700", marginBottom: 4 },
    modalSub: { fontSize: 11, color: colors.silver, opacity: 0.5, marginBottom: 12 },
    toggle: {
      flexDirection: "row",
      marginBottom: 14,
      backgroundColor: colors.bg3,
      borderRadius: 14,
      padding: 4,
      gap: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    togBtn: { flex: 1, padding: 9, borderRadius: 10, alignItems: "center" },
    togBtnExpense: { backgroundColor: colors.dangerDim },
    togBtnIncome: { backgroundColor: colors.successDim },
    togText: { fontSize: 11, fontWeight: "600", color: colors.silver },
    inputLabel: { fontSize: 9, color: colors.silver, opacity: 0.4, letterSpacing: 2, textTransform: "uppercase", marginBottom: 6, marginTop: 10 },
    input: { backgroundColor: colors.bg3, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 12, color: colors.textPrimary, fontSize: 14 },
    catGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 4 },
    catItem: { width: "22%", backgroundColor: colors.bg3, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 10, alignItems: "center", gap: 4 },
    catItemSelected: { backgroundColor: colors.dangerDim, borderColor: colors.danger },
    catName: { fontSize: 8, color: colors.silver, opacity: 0.5, textAlign: "center" },
    modalBtns: { flexDirection: "row", gap: 10, marginTop: 16 },
    modalCancelBtn: { flex: 1, padding: 14, borderRadius: 12, backgroundColor: colors.bg3, borderWidth: 1, borderColor: colors.border, alignItems: "center" },
    modalCancelText: { color: colors.silver, fontWeight: "600" },
    modalSaveBtn: { flex: 2, padding: 14, borderRadius: 12, backgroundColor: colors.electric, alignItems: "center" },
    modalSaveText: { color: "#fff", fontWeight: "700", fontSize: 14 },
    actionBar: {
      flexDirection: "row",
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
      backgroundColor: colors.bg0,
      borderTopWidth: 1,
      borderTopColor: colors.border2,
    },
    actionPill: { flex: 1, backgroundColor: colors.bg3, borderWidth: 1, borderColor: colors.border, borderRadius: 12, paddingVertical: 8, alignItems: "center", gap: 4 },
    actionPillActive: { borderColor: colors.accent, backgroundColor: colors.accentDim },
    actionPillIco: { fontSize: 16 },
    actionPillTxt: { fontSize: 8, color: colors.silver, opacity: 0.5, letterSpacing: 0.5, textTransform: "uppercase" },
    actionPillTxtActive: { color: colors.accent, opacity: 1 },
    bottomNav: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      flexDirection: "row",
      justifyContent: "space-around",
      paddingTop: 10,
      paddingBottom: 28,
      paddingHorizontal: 8,
      backgroundColor: colors.bg1,
      borderTopWidth: 0.5,
      borderTopColor: colors.border,
    },
    navItem: { alignItems: "center", gap: 3 },
    navIcon: { fontSize: 20, opacity: 0.3 },
    navIconActive: { opacity: 1 },
    navDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: colors.accent, opacity: 0 },
    navDotActive: { opacity: 1 },
    navLabel: { fontSize: 8, color: colors.silver, opacity: 0.3, letterSpacing: 1, textTransform: "uppercase" },
    navLabelActive: { color: colors.accent, opacity: 1 },

    navPlusBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.accent,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 2,
    },
    navPlusBtnInactive: { opacity: 0.6 },
    navPlusLabel: {
      fontSize: 8,
      fontWeight: "700",
      color: colors.accent,
      marginTop: 2,
      opacity: 1,
    },
    navPlusLabelInactive: { opacity: 0.6 },
  });

export default makeStyles;